### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by sadielbartholomew** [ES-DOC/pyesdoc#17]
Much overdue, especially as we are now sitting on some high-severity security vulnerabilities (in `urllib3` and `lxml`) which can't be resolved automatically by Dependabot, which requires Python 3, so would need manual compatibility verification (which seems risky and time-consuming!).

I would like to tackle this migration straight after the machine and performance work is released, before starting the conformance work in earnest, because use of Python 2 slowed me down greatly with the former in terms of difficulty of setting up a compatible environment across essential libraries and changing code I write naturally in 3 to work with Python 2.

**Comment by sadielbartholomew** [comment]
This didn't happen a few years ago for various reasons (mostly lack of dedicated time) but I am tackling this now.

**Comment by davidhassell** [comment]
Agreed.
